#!/usr/bin/env bash 

TWARS="../"
export PATH=$(pwd)/webdrivers:$PATH


read -r -d '\n' USAGE <<'ENF'
    用法: (init|run) 
    1. init 初始化环境并运行测试
    2. run 运行测试
ENF

command_exists() {
  command -v "$@" > /dev/null 2>&1
}


output() {
	cowsay $@ | lolcat
}

run_container() {
	output "Start Containers"
  pwd
	cd $TWARS/assembly/ || exit 1
	docker-compose kill && docker-compose up -d 
}

refreshMongo() {
	output "Refresh Mongo"
	pwd
	cd $TWARS/web-api || exit 1
	npm run refreshMongo
}

refreshMysql() {
	output "Refresh MySQL"
	pwd
	cd $TWARS/paper-api/ || exit 1
  docker exec -i assembly_mysql_1 mysql -uroot -pthoughtworks BronzeSword < ./BronzeSword.sql
}

refreshDB() {
	refreshMongo && refreshMysql
}


run_test() {
	output "Execute Test"
	cd $TWARS/automated-test || exit 1
	./gradlew clean test
}

initialize() {
	run_container && refreshDB
}

init() {
	initialize && run_test
}

run() {
	refreshDB && run_test
}



action=$1

case $action in 
	init)
		output "Initialize Execution Environment"
		init
		;;
	run)
		output "Run Test"
		run
		;;
	*)
		output $USAGE
		;;
esac
		

