#!/usr/bin/env sh

TWARS="../"
export PATH=$(pwd)/webdrivers:$PATH

color_echo () {
	echo "\033[1;32;40m $@ \033[0m"
}

command_exists() {
  command -v "$@" > /dev/null 2>&1
}

command_exists cowsay && alias cowsay="cowsay -f gnu" || alias cowsay=color_echo

run_container() {
	cowsay "Start Containers"
  pwd
	cd $TWARS/assembly/ || exit 1
	docker-compose kill && docker-compose up -d 
}

refreshMongo() {
	cowsay "Refresh Mongo"
	pwd
	cd $TWARS/web-api || exit 1
	npm run refreshMongo
}

refreshMysql() {
	cowsay "Refresh MySQL"
	pwd
	cd $TWARS/paper-api/ || exit 1
  docker exec -i assembly_mysql_1 mysql -uroot -pthoughtworks BronzeSword < ./BronzeSword.sql
}

refreshDB() {
	refreshMongo && refreshMysql
}


run_test() {
	cowsay "Execute Test"
	cd $TWARS/automated-test || exit 1
	./gradlew clean test
}

initialize() {
	run_container && refreshDB
}

init() {
	initialize && run_test
}

run() {
	refreshDB && run_test
}



action=$1

case $action in 
	init)
		cowsay "Initialize Execution Environment"
		init
		;;
	run)
		cowsay "Run Test"
		run
		;;
	*)
		color_echo "用法: (init|run)"
		color_echo "- command: "
		color_echo "init 初始化环境并运行测试"
		color_echo "run 运行测试"
		;;
esac
		

